### ISSUE TITLE
`typeof` check blows up

### ISSUE THREAD

**Issue by tomaratyn** [bevacqua/ticky#1]
There's a small typo that causes the `typeof` check to blow up. It should be checking for the string `'undefined'` not `undef`.

**Comment by drochgenius** [comment]
I am trying to bundle dragula.js in my app with either rollup or browserify, and I keep getting a related error at runtime.

undef is undefined in ticky.js

Is the solution to set undef='undefined'?

**Comment by bevacqua** [comment]
`1.0.1`
